[package]
name = "lego"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
palette = { version = "0.7.6", features = ["serializing"] }
serde = { version = "1.0.219", features = ["derive"] }
sprs = { version = "0.11.3", features = ["serde"] }
rayon = "1.10"
